### ISSUE TITLE
write statement error

### ISSUE THREAD

**Issue by jurnix** [mbdevpl/open-fortran-parser-xml#5] opened 2017-09-11 12:24 UTC
The error message:
```bash
java fortran.ofp.FrontEnd --class fortran.ofp.XMLPrinter --output tree.xml --verbosity 100 src_sechiba/intersurf.f90 src_sechiba/intersurf.f90 line 1299:42 no viable alternative at input ','
```

Line where it fails:
```fortran
    IF (printlev_loc >=2)  WRITE(numout,*),'tau_outflow, coeff_rel = ', tau_outflow, coeff_rel
```

The whole file:
https://pastebin.com/EJmG32ee

**Comment by mbdevpl** [comment] 2017-09-27 10:03
Unfortunately this error seems to come from upstream https://github.com/OpenFortranProject/open-fortran-parser - in which they haven't been fixing any issues...

Basically any `no viable alternative at input` comes from the OFP itself, not from the XML generator.

**Comment by jurnix** [comment] 2017-10-10 12:42
For this case, it is not a big deal.

**Comment by mbdevpl** [comment] 2017-12-10 08:33
I had some time to diagnose this issue in detail. The problem is that:
`WRITE(numout,*),'tau...` should in fact be:
`WRITE(numout,*) 'tau...`
i.e. there shouldn't be a comma immediately after the closing parenthesis of `WRITE`. For examples, see here: http://www.oc.nps.edu/~bird/oc3030_online/fortran/io/io.html . Open Fortran Parser maybe doesn't do a good job at suggesting the exact reason for some issue, but after all it writes that:

`src_sechiba/intersurf.f90 line 1299:42 no viable alternative at input ','` - which would basically mean, that `there's a ',' where it shouldn't be`.

I've added this example as `test/examples/problematic_write.f90` where after fixing the syntax the code is parsed correctly. Therefore I'm closing this as non-issue.

**Closed as completed by mbdevpl** 2017-12-10 08:33 UTC
